name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make -j2

      - name: Check help output
        run: |
          ./bin/mpc-mpcx-ip-writer --help
          ./bin/mpc-mpcx-ip-reader --help
          ./bin/mpc-mpcx-ip-command --help
